approve:
- commandHelpLink: ""
  repos:
  - openshift/velero-plugin-for-aws
  require_self_approval: false
lgtm:
- repos:
  - openshift/velero-plugin-for-aws
plugins:
  openshift/velero-plugin-for-aws:
    plugins:
    - approve
owners:
  filenames:
    openshift/velero-plugin-for-aws:
      owners: OPENSHIFT_OWNERS
      owners_aliases: OPENSHIFT_OWNERS_ALIASES
