approve:
- commandHelpLink: ""
  repos:
  - openshift/velero
  require_self_approval: false
lgtm:
- repos:
  - openshift/velero
plugins:
  openshift/velero:
    plugins:
    - approve
owners:
  filenames:
    openshift/velero:
      owners: OPENSHIFT_OWNERS
      owners_aliases: OPENSHIFT_OWNERS_ALIASES
