build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.22-openshift-4.17
images:
- dockerfile_path: Dockerfile
  to: openshift-velero-plugin-oadp-1.4
promotion:
  to:
  - name: openshift-velero-plugin
    namespace: konveyor
releases:
  latest:
    release:
      channel: fast
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit-test
  steps:
    test:
    - as: unit
      commands: GOFLAGS="-mod=mod" make test
      from: quay.io/konveyor/builder:ubi9-v1.22
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
zz_generated_metadata:
  branch: oadp-1.4
  org: openshift
  repo: openshift-velero-plugin
